In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
import sys

from pathlib import Path

# Add the root directory of the project to the Python path of the notebook's session
project_root = Path.cwd().parent  # Assuming the notebook is in the "notebooks" folder
sys.path.append(str(project_root))

# Import function for loading preprocessed data
from src.Preprocessing.utils import load_preprocessed_data, transform_to_tensor, save_preprocessed_data

In [9]:
data_directory = project_root / "data" / "preprocessed" / "Dog_1"
print("Directory of the data: ")
print(data_directory)

Directory of the data: 
c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1


## Frequency Domain

In [10]:
file_name = "freq_domain_train.npz"

freq_domain_preprocessed = load_preprocessed_data(data_directory, file_name)

X_train_freq = freq_domain_preprocessed["X"]
y_train_freq = freq_domain_preprocessed["y"]

print("Number of slices: ", len(X_train_freq))

print(X_train_freq)

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\freq_domain_train.npz
Number of slices:  10080
[{'delta_mean': array([3.86088277, 3.69929204, 3.79844679, 3.7614892 , 3.80070317,
        3.57091407, 3.72508142, 3.72632327, 3.81148434, 3.67766162,
        3.56334622, 3.67775332, 3.83689165, 3.61381349, 3.65113957,
        3.72855931]), 'delta_std': array([0.25313124, 0.30358259, 0.30488416, 0.31064912, 0.26284323,
        0.30009964, 0.34379839, 0.2747996 , 0.26850826, 0.28619907,
        0.26151922, 0.26320181, 0.27720275, 0.30441275, 0.26347024,
        0.29038639]), 'theta_mean': array([3.74026402, 3.61457315, 3.51855968, 3.64013039, 3.58692677,
        3.42097063, 3.51769658, 3.46424254, 3.66404604, 3.4383492 ,
        3.3980832 , 3.51560034, 3.65630806, 3.49531712, 3.4690012 ,
        3.60868276]), 'theta_std': array([0.32364167, 0.27772096, 0.28990199, 0.26221081, 0.31921086,
        0.29361066, 0.25904511, 0.31230111, 0.2624018 , 0.3036

In [11]:
X_train0_freq = X_train_freq[0]

print("Features for every channel: ")
print(list(X_train0_freq.keys()))

print("Value for key 'delta_mean': ")
print(X_train0_freq["delta_mean"])

Features for every channel: 
['delta_mean', 'delta_std', 'theta_mean', 'theta_std', 'alpha_mean', 'alpha_std', 'beta_mean', 'beta_std', 'low_gamma_mean', 'low_gamma_std', 'mid_gamma_mean', 'mid_gamma_std', 'high_gamma_1_mean', 'high_gamma_1_std', 'high_gamma_2_mean', 'high_gamma_2_std']
Value for key 'delta_mean': 
[3.86088277 3.69929204 3.79844679 3.7614892  3.80070317 3.57091407
 3.72508142 3.72632327 3.81148434 3.67766162 3.56334622 3.67775332
 3.83689165 3.61381349 3.65113957 3.72855931]


In [12]:
X_train0_freq_df = pd.DataFrame(X_train_freq[0])
X_train0_freq_df.head()

delta_mean  delta_std  theta_mean  theta_std  alpha_mean  alpha_std  \
0    3.860883   0.253131    3.740264   0.323642    3.545684   0.287894   
1    3.699292   0.303583    3.614573   0.277721    3.516531   0.265756   
2    3.798447   0.304884    3.518560   0.289902    3.410249   0.287694   
3    3.761489   0.310649    3.640130   0.262211    3.528653   0.284350   
4    3.800703   0.262843    3.586927   0.319211    3.349720   0.295590   

   beta_mean  beta_std  low_gamma_mean  low_gamma_std  mid_gamma_mean  \
0   3.500910  0.276814        3.415099       0.289872        3.230648   
1   3.388776  0.280770        3.351585       0.273382        3.175433   
2   3.285220  0.261799        3.226586       0.309864        3.080569   
3   3.366406  0.270879        3.305900       0.286259        3.142568   
4   3.369538  0.276502        3.325118       0.285174        3.181188   

   mid_gamma_std  high_gamma_1_mean  high_gamma_1_std  high_gamma_2_mean  \
0       0.265392           3.005063          0.292402           2.595448   
1       0.286158           2.977510          0.292089           2.574946   
2       0.290002           2.904999          0.276862           2.544502   
3       0.281287           2.941553          0.299685           2.594057   
4       0.281649           2.978383          0.272462           2.608836   

   high_gamma_2_std  
0          0.315658  
1          0.327762  
2          0.315481  
3          0.310177  
4          0.309739

In [13]:
steps = 8

X_train_freq_tensor, y_train_freq_tensor = transform_to_tensor(X_train_freq, y_train_freq, steps=steps)

print("Number of slices: ", len(X_train_freq))
print("Steps: ", steps)
print("Shape of the tensor X_freq: ", X_train_freq_tensor.shape)
print("Shape of the tensor y_freq: ", y_train_freq_tensor.shape)

print("tensor: ", X_train_freq_tensor)

Number of slices:  10080
Steps:  8
Shape of the tensor X_freq:  (1260, 16, 16, 8)
Shape of the tensor y_freq:  (1260,)
tensor:  tf.Tensor(
[[[[3.8608828  3.8448725  3.7824528  ... 3.8499513  3.7951238
    3.8070314 ]
   [0.25313124 0.27153903 0.3084179  ... 0.32915196 0.29338273
    0.25320688]
   [3.740264   3.7419329  3.6909974  ... 3.716844   3.6004674
    3.657331  ]
   ...
   [0.29240248 0.3094082  0.26101238 ... 0.29801184 0.273477
    0.27851334]
   [2.5954478  2.579718   2.6130345  ... 2.567423   2.5355434
    2.5600183 ]
   [0.3156577  0.31446722 0.31714818 ... 0.3208481  0.31294915
    0.3192028 ]]

  [[3.699292   3.7372122  3.6501362  ... 3.729133   3.702566
    3.6823347 ]
   [0.3035826  0.29952234 0.26815268 ... 0.30386645 0.28535023
    0.30610272]
   [3.6145732  3.5990405  3.5896225  ... 3.6995177  3.6162837
    3.5255258 ]
   ...
   [0.2920887  0.2847382  0.29796323 ... 0.30882928 0.28923643
    0.28086916]
   [2.574946   2.5541925  2.5779233  ... 2.530379   2.530184
  

In [12]:
print("First part of the segment: ")
pd.DataFrame(X_train_freq_tensor[0, :, :, 0]).head()

First part of the segment: 


0         1         2         3         4         5         6   \
0  3.860883  0.253131  3.740264  0.323642  3.545684  0.287894  3.500910   
1  3.699292  0.303583  3.614573  0.277721  3.516531  0.265756  3.388776   
2  3.798447  0.304884  3.518560  0.289902  3.410249  0.287694  3.285220   
3  3.761489  0.310649  3.640130  0.262211  3.528653  0.284350  3.366406   
4  3.800703  0.262843  3.586927  0.319211  3.349720  0.295590  3.369538   

         7         8         9         10        11        12        13  \
0  0.276814  3.415099  0.289872  3.230648  0.265392  3.005063  0.292402   
1  0.280770  3.351585  0.273382  3.175433  0.286158  2.977510  0.292089   
2  0.261799  3.226586  0.309864  3.080569  0.290002  2.904999  0.276862   
3  0.270879  3.305900  0.286259  3.142568  0.281287  2.941553  0.299685   
4  0.276502  3.325118  0.285174  3.181188  0.281649  2.978383  0.272462   

         14        15  
0  2.595448  0.315658  
1  2.574946  0.327762  
2  2.544502  0.315481  
3  2.594057  0.310177  
4  2.608835  0.309739

## Time Domain

In [13]:
file_name = "time_domain_test.npz"

time_domain_preprocessed = load_preprocessed_data(data_directory, file_name)

X_train_time = time_domain_preprocessed["X"]
y_train_time = time_domain_preprocessed["y"]

print("Number of slices: ", len(X_train_time))
print("Features for every channel: ")
print(X_train_time)

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\time_domain_test.npz
Number of slices:  10040
Features for every channel: 
[{'pc1': array([3.68962866, 3.46377263, 2.25185598, 3.12865134, 3.50602968,
        3.28036392, 2.22211923, 2.97649202, 2.30477215, 2.93958111,
        3.21787045, 3.29646858, 2.96363063, 3.19076047, 3.26871549,
        3.29790954]), 'pc2': array([2.73298439, 2.84373245, 3.33885916, 3.34949836, 1.32734831,
        2.82673415, 3.16443312, 3.17350432, 3.53752476, 3.36300609,
        2.83793918, 1.99361136, 3.22929833, 2.8912964 , 1.46706277,
        2.75614875]), 'pc3': array([3.20837715, 3.29985674, 3.33310606, 2.6873682 , 3.27987383,
        2.13456499, 2.96709319, 1.47949326, 3.12015933, 3.11107737,
        2.23777747, 3.19582935, 2.73662501, 2.43401036, 3.13452531,
        3.28450838]), 'pc4': array([2.24517789, 3.42474871, 2.67043055, 2.92397281, 3.15720415,
        2.62772474, 2.8267806 , 2.84847883, 2.67333624, 2.30

In [15]:
steps = 4

X_train_time_tensor, y_train_time_tensor = transform_to_tensor(X_train_time, y_train_time, steps=steps)

In [17]:
X_train_time_tensor

<tf.Tensor: shape=(2510, 16, 16, 4), dtype=float32, numpy=
array([[[[  3.6896286 ,   3.7183647 ,   3.6990774 ,   3.644319  ],
         [  2.7329843 ,   2.6232297 ,   2.7130983 ,   3.041187  ],
         [  3.2083771 ,   3.1699574 ,   3.2180433 ,   3.1357803 ],
         ...,
         [ -1.3157835 ,   0.47452068,   0.06231767,   0.05221611],
         [ -0.71581334,   0.8135702 ,  -0.25272647,   0.73898757],
         [-11.979841  , -12.158598  , -11.934919  , -11.916185  ]],

        [[  3.4637725 ,   3.451792  ,   3.5248532 ,   3.5165052 ],
         [  2.8437324 ,   2.9092436 ,   2.8681889 ,   2.5644224 ],
         [  3.2998567 ,   3.4127548 ,   3.3708556 ,   3.3364708 ],
         ...,
         [  0.44280088,   1.0554607 ,   1.1565434 ,   0.37553033],
         [  0.07053347,   0.92597157,   0.8412253 ,   0.6645129 ],
         [-11.979841  , -12.158598  , -11.934919  , -11.916185  ]],

        [[  2.251856  ,   2.1403418 ,   2.468761  ,   2.027585  ],
         [  3.338859  ,   3.0880353 , 

In [18]:
X_train0_time = X_train_time_tensor[0, :, :, 0]

print("First part of the segment: ")
X_train0_time = pd.DataFrame(X_train0_time)
X_train0_time.head()

First part of the segment: 


0         1         2         3         4         5         6   \
0  3.689629  2.732984  3.208377  2.245178  3.075347  3.111947  2.754742   
1  3.463773  2.843732  3.299857  3.424749  2.503730  2.382418  2.863874   
2  2.251856  3.338859  3.333106  2.670431  2.408042  2.543447  2.995252   
3  3.128651  3.349498  2.687368  2.923973  3.224902  0.393152  3.053553   
4  3.506030  1.327348  3.279874  3.157204  2.853808  2.884254  2.760733   

         7         8         9         10        11        12        13  \
0  2.489569  2.228254  1.897635  1.756742  1.398644  1.059396 -1.315784   
1  1.757203  1.826882  2.213494  2.070897  1.482369  1.823484  0.442801   
2  2.943740  2.450964  2.593613  2.124110  0.284420  2.321367  2.000878   
3  2.302179  2.406617  2.363870  2.254024  1.578451  2.116318  2.129127   
4  2.872504  2.316370  2.580497  2.428981  1.985622  1.891454  1.602314   

         14         15  
0 -0.715813 -11.979841  
1  0.070533 -11.979841  
2  1.420662 -11.979841  
3  1.106363 -11.979841  
4  0.926774 -11.979841