In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import sys

from pathlib import Path

# Add the root directory of the project to the Python path of the notebook's session
project_root = Path.cwd().parent  # Assuming the notebook is in the "notebooks" folder
sys.path.append(str(project_root))

# Import function for loading preprocessed data
from src.Preprocessing.utils import load_preprocessed_data, transform_to_tensor, save_preprocessed_data

In [2]:
data_directory = project_root / "data" / "preprocessed" / "Dog_1"
print("Directory of the data: ")
print(data_directory)

Directory of the data: 
c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1


## Frequency Domain Train

In [7]:
file_name = "freq_domain_train.npz"

freq_domain_preprocessed = load_preprocessed_data(data_directory, file_name)

X_train_freq = freq_domain_preprocessed["X"]
y_train_freq = freq_domain_preprocessed["y"]

print("Number of slices: ", len(X_train_freq))

print(X_train_freq)

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\freq_domain_train.npz
Number of slices:  10080
[{'delta_mean': array([3.86088277, 3.69929204, 3.79844679, 3.7614892 , 3.80070317,
        3.57091407, 3.72508142, 3.72632327, 3.81148434, 3.67766162,
        3.56334622, 3.67775332, 3.83689165, 3.61381349, 3.65113957,
        3.72855931]), 'delta_std': array([0.25313124, 0.30358259, 0.30488416, 0.31064912, 0.26284323,
        0.30009964, 0.34379839, 0.2747996 , 0.26850826, 0.28619907,
        0.26151922, 0.26320181, 0.27720275, 0.30441275, 0.26347024,
        0.29038639]), 'theta_mean': array([3.74026402, 3.61457315, 3.51855968, 3.64013039, 3.58692677,
        3.42097063, 3.51769658, 3.46424254, 3.66404604, 3.4383492 ,
        3.3980832 , 3.51560034, 3.65630806, 3.49531712, 3.4690012 ,
        3.60868276]), 'theta_std': array([0.32364167, 0.27772096, 0.28990199, 0.26221081, 0.31921086,
        0.29361066, 0.25904511, 0.31230111, 0.2624018 , 0.3036

In [8]:
X_train0_freq = X_train_freq[0]

print("Features for every channel: ")
print(list(X_train0_freq.keys()))

print("Value for key 'delta_mean': ")
print(X_train0_freq["delta_mean"])

Features for every channel: 
['delta_mean', 'delta_std', 'theta_mean', 'theta_std', 'alpha_mean', 'alpha_std', 'beta_mean', 'beta_std', 'low_gamma_mean', 'low_gamma_std', 'mid_gamma_mean', 'mid_gamma_std', 'high_gamma_1_mean', 'high_gamma_1_std', 'high_gamma_2_mean', 'high_gamma_2_std']
Value for key 'delta_mean': 
[3.86088277 3.69929204 3.79844679 3.7614892  3.80070317 3.57091407
 3.72508142 3.72632327 3.81148434 3.67766162 3.56334622 3.67775332
 3.83689165 3.61381349 3.65113957 3.72855931]


In [9]:
X_train0_freq_df = pd.DataFrame(X_train_freq[0])
X_train0_freq_df.head()

delta_mean  delta_std  theta_mean  theta_std  alpha_mean  alpha_std  \
0    3.860883   0.253131    3.740264   0.323642    3.545684   0.287894   
1    3.699292   0.303583    3.614573   0.277721    3.516531   0.265756   
2    3.798447   0.304884    3.518560   0.289902    3.410249   0.287694   
3    3.761489   0.310649    3.640130   0.262211    3.528653   0.284350   
4    3.800703   0.262843    3.586927   0.319211    3.349720   0.295590   

   beta_mean  beta_std  low_gamma_mean  low_gamma_std  mid_gamma_mean  \
0   3.500910  0.276814        3.415099       0.289872        3.230648   
1   3.388776  0.280770        3.351585       0.273382        3.175433   
2   3.285220  0.261799        3.226586       0.309864        3.080569   
3   3.366406  0.270879        3.305900       0.286259        3.142568   
4   3.369538  0.276502        3.325118       0.285174        3.181188   

   mid_gamma_std  high_gamma_1_mean  high_gamma_1_std  high_gamma_2_mean  \
0       0.265392           3.005063          0.292402           2.595448   
1       0.286158           2.977510          0.292089           2.574946   
2       0.290002           2.904999          0.276862           2.544502   
3       0.281287           2.941553          0.299685           2.594057   
4       0.281649           2.978383          0.272462           2.608836   

   high_gamma_2_std  
0          0.315658  
1          0.327762  
2          0.315481  
3          0.310177  
4          0.309739

In [10]:
steps = 8

X_train_freq_tensor, y_train_freq_tensor = transform_to_tensor(X_train_freq, y_train_freq, steps=steps)

print("Number of slices: ", len(X_train_freq))
print("Steps: ", steps)
print("Shape of the tensor X_freq: ", X_train_freq_tensor.shape)
print("Shape of the tensor y_freq: ", y_train_freq_tensor.shape)

print("tensor: ", X_train_freq_tensor)

Number of slices:  10080
Steps:  8
Shape of the tensor X_freq:  (1260, 16, 16, 8)
Shape of the tensor y_freq:  (1260,)
tensor:  tf.Tensor(
[[[[3.8608828  3.8448725  3.7824528  ... 3.8499513  3.7951238
    3.8070314 ]
   [0.25313124 0.27153903 0.3084179  ... 0.32915196 0.29338273
    0.25320688]
   [3.740264   3.7419329  3.6909974  ... 3.716844   3.6004674
    3.657331  ]
   ...
   [0.29240248 0.3094082  0.26101238 ... 0.29801184 0.273477
    0.27851334]
   [2.5954478  2.579718   2.6130345  ... 2.567423   2.5355434
    2.5600183 ]
   [0.3156577  0.31446722 0.31714818 ... 0.3208481  0.31294915
    0.3192028 ]]

  [[3.699292   3.7372122  3.6501362  ... 3.729133   3.702566
    3.6823347 ]
   [0.3035826  0.29952234 0.26815268 ... 0.30386645 0.28535023
    0.30610272]
   [3.6145732  3.5990405  3.5896225  ... 3.6995177  3.6162837
    3.5255258 ]
   ...
   [0.2920887  0.2847382  0.29796323 ... 0.30882928 0.28923643
    0.28086916]
   [2.574946   2.5541925  2.5779233  ... 2.530379   2.530184
  

In [11]:
print("First part of the segment: ")
pd.DataFrame(X_train_freq_tensor[0, :, :, 0]).head()

First part of the segment: 


0         1         2         3         4         5         6   \
0  3.860883  0.253131  3.740264  0.323642  3.545684  0.287894  3.500910   
1  3.699292  0.303583  3.614573  0.277721  3.516531  0.265756  3.388776   
2  3.798447  0.304884  3.518560  0.289902  3.410249  0.287694  3.285220   
3  3.761489  0.310649  3.640130  0.262211  3.528653  0.284350  3.366406   
4  3.800703  0.262843  3.586927  0.319211  3.349720  0.295590  3.369538   

         7         8         9         10        11        12        13  \
0  0.276814  3.415099  0.289872  3.230648  0.265392  3.005063  0.292402   
1  0.280770  3.351585  0.273382  3.175433  0.286158  2.977510  0.292089   
2  0.261799  3.226586  0.309864  3.080569  0.290002  2.904999  0.276862   
3  0.270879  3.305900  0.286259  3.142568  0.281287  2.941553  0.299685   
4  0.276502  3.325118  0.285174  3.181188  0.281649  2.978383  0.272462   

         14        15  
0  2.595448  0.315658  
1  2.574946  0.327762  
2  2.544502  0.315481  
3  2.594057  0.310177  
4  2.608835  0.309739

## Time Domain Train

In [12]:
file_name = "time_domain_train.npz"

time_domain_preprocessed = load_preprocessed_data(data_directory, file_name)

X_train_time = time_domain_preprocessed["X"]
y_train_time = time_domain_preprocessed["y"]

print("Number of slices: ", len(X_train_time))
print("Features for every channel: ")
print(X_train_time)

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\time_domain_train.npz
Number of slices:  10080
Features for every channel: 
[{'pc1': array([3.14343124, 3.04868057, 2.93749289, 2.93062298, 3.04507777,
        2.95959165, 2.90091313, 2.91894951, 3.140064  , 3.15832283,
        2.87349487, 1.80238202, 3.49388459, 3.08425634, 2.25891061,
        2.43190903]), 'pc2': array([3.21121845, 2.98384044, 2.3792283 , 2.98578732, 3.11646768,
        2.89302506, 2.34779919, 2.88506361, 2.97979386, 2.56814349,
        2.85674924, 3.11845687, 3.02967103, 2.78516586, 3.07813825,
        3.17107961]), 'pc3': array([3.07570223, 1.88774932, 3.09317794, 3.01760049, 2.78970683,
        2.49270151, 3.02087666, 2.99700973, 2.55819912, 1.9691515 ,
        2.38140224, 2.91524144, 2.83384678, 2.20441668, 2.92790344,
        3.03875293]), 'pc4': array([2.20326576, 2.53721232, 2.30671015, 3.03504773, 2.0535966 ,
        2.58583622, 3.01403007, 2.43168461, 3.05920564, 2.0

In [13]:
steps = 4

X_train_time_tensor, y_train_time_tensor = transform_to_tensor(X_train_time, y_train_time, steps=steps)

In [14]:
X_train_time_tensor

<tf.Tensor: shape=(2520, 16, 16, 4), dtype=float32, numpy=
array([[[[ 3.1434312e+00,  3.2176368e+00,  2.8723414e+00,
           2.7425854e+00],
         [ 3.2112184e+00,  3.0674317e+00,  3.2393110e+00,
           3.2701874e+00],
         [ 3.0757022e+00,  3.0917501e+00,  3.0569167e+00,
           2.9960761e+00],
         ...,
         [ 1.5887877e+00,  9.8594427e-01,  1.3963199e+00,
           1.5945001e+00],
         [-5.3292996e-01,  9.6192092e-01,  8.0415362e-01,
           5.8711988e-01],
         [-1.2150851e+01, -1.2179293e+01, -1.2288362e+01,
          -1.2033110e+01]],

        [[ 3.0486805e+00,  3.1590426e+00,  2.8423519e+00,
           2.7286978e+00],
         [ 2.9838405e+00,  2.8516667e+00,  3.0910103e+00,
           3.1238363e+00],
         [ 1.8877493e+00,  1.2735853e+00,  1.9958744e+00,
           1.4184664e+00],
         ...,
         [ 1.7461941e+00,  1.4081969e+00,  1.6869919e+00,
           1.8880793e+00],
         [ 1.2254529e-01,  8.8066095e-01,  8.3396286e-01,
   

In [15]:
X_train0_time = X_train_time_tensor[0, :, :, 0]

print("First part of the segment: ")
X_train0_time = pd.DataFrame(X_train0_time)
X_train0_time.head()

First part of the segment: 


0         1         2         3         4         5         6   \
0  3.143431  3.211218  3.075702  2.203266  2.750378  2.430432  2.556178   
1  3.048681  2.983840  1.887749  2.537212  2.765255  3.069025  2.733554   
2  2.937493  2.379228  3.093178  2.306710  2.452029  2.661938  1.909554   
3  2.930623  2.985787  3.017601  3.035048  2.696918  2.399433  1.856555   
4  3.045078  3.116468  2.789707  2.053596  2.193357  2.867617  2.125741   

         7         8         9         10        11        12        13  \
0  2.709589  2.826022  1.900633  1.605318 -0.008401  1.812562  1.588788   
1  2.372650  2.705566  1.604023  0.653533  0.185410  2.022786  1.746194   
2  2.909717  2.827105  2.499948  1.472634  1.209351  1.392374  0.571016   
3  2.357911  2.079626  2.794330  2.243201  1.810169  1.444030  1.402019   
4  2.851568  2.647869  2.016420  0.340748  1.818309  2.469710  2.086541   

         14         15  
0 -0.532930 -12.150851  
1  0.122545 -12.150851  
2  1.383795 -12.150851  
3  1.212710 -12.150851  
4  1.087176 -12.150851

In [17]:
labels_train_freq = np.array(y_train_freq)
labels_train_time = np.array(y_train_time)

assert np.array_equal(labels_train_freq, labels_train_time)

## Test Data

In [3]:
filename = "freq_domain_test.npz"
data_test_freq = load_preprocessed_data(data_directory, filename)

print("Number of slices: ", len(data_test_freq["X"]))
print("Number of labels: ", len(data_test_freq["y"]))

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\freq_domain_test.npz
Number of slices:  10040
Number of labels:  10040


In [4]:
filename = "time_domain_test.npz"
data_test_time = load_preprocessed_data(data_directory, filename)

print("Number of slices: ", len(data_test_time["X"]))
print("Number of labels: ", len(data_test_time["y"]))

Data loaded from c:\Users\lucas\Documents\Python Projects\SeizureSen\data\preprocessed\Dog_1\time_domain_test.npz
Number of slices:  10040
Number of labels:  10040


In [5]:
labels_test_freq = np.array(data_test_freq["y"])
labels_test_time = np.array(data_test_time["y"])

assert np.array_equal(labels_test_freq, labels_test_time)

In [20]:
steps = 4
transform_to_tensor(data_test_freq["X"], data_test_freq["y"], steps=steps)

(<tf.Tensor: shape=(2510, 16, 16, 4), dtype=float32, numpy=
 array([[[[4.239215  , 4.26519   , 4.2165103 , 4.194985  ],
          [0.30236217, 0.28499994, 0.3812618 , 0.30290484],
          [4.0558643 , 4.115196  , 4.1171894 , 4.0340652 ],
          ...,
          [0.28668898, 0.29238895, 0.28180873, 0.2949186 ],
          [2.3738482 , 2.3801627 , 2.3584077 , 2.374012  ],
          [0.3257848 , 0.32259014, 0.3131408 , 0.32382473]],
 
         [[4.2171974 , 4.2060227 , 4.2314777 , 4.194562  ],
          [0.33117065, 0.31916726, 0.30605343, 0.3263965 ],
          [3.97542   , 3.9830246 , 4.02951   , 3.9929557 ],
          ...,
          [0.28453895, 0.28676492, 0.29217604, 0.29601836],
          [2.375648  , 2.3732364 , 2.3875785 , 2.3791106 ],
          [0.3112539 , 0.31814328, 0.30398196, 0.32745752]],
 
         [[4.09191   , 4.0615745 , 4.0556116 , 4.0204716 ],
          [0.34482983, 0.26816073, 0.2973102 , 0.2708767 ],
          [3.8594093 , 3.8300853 , 3.8411477 , 3.7919834 ],
    

In [21]:
transform_to_tensor(data_test_time["X"], data_test_time["y"], steps=steps)

(<tf.Tensor: shape=(2510, 16, 16, 4), dtype=float32, numpy=
 array([[[[  3.6896286 ,   3.7183647 ,   3.6990774 ,   3.644319  ],
          [  2.7329843 ,   2.6232297 ,   2.7130983 ,   3.041187  ],
          [  3.2083771 ,   3.1699574 ,   3.2180433 ,   3.1357803 ],
          ...,
          [ -1.3157835 ,   0.47452068,   0.06231767,   0.05221611],
          [ -0.71581334,   0.8135702 ,  -0.25272647,   0.73898757],
          [-11.979841  , -12.158598  , -11.934919  , -11.916185  ]],
 
         [[  3.4637725 ,   3.451792  ,   3.5248532 ,   3.5165052 ],
          [  2.8437324 ,   2.9092436 ,   2.8681889 ,   2.5644224 ],
          [  3.2998567 ,   3.4127548 ,   3.3708556 ,   3.3364708 ],
          ...,
          [  0.44280088,   1.0554607 ,   1.1565434 ,   0.37553033],
          [  0.07053347,   0.92597157,   0.8412253 ,   0.6645129 ],
          [-11.979841  , -12.158598  , -11.934919  , -11.916185  ]],
 
         [[  2.251856  ,   2.1403418 ,   2.468761  ,   2.027585  ],
          [  3.33885